dist: xenial
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - &pypy2 pypy2.7-6.0
  - &pypy3 pypy3.5-6.0
install:
  - pip install cffi
script:
  - make test
branches:
  only:
  - master
  - "6.40"
